[package]
name = "vaab-vm"
description = "The Vaab bytecode compiler and virtual machine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
indexmap.workspace = true
vaab-syntax.workspace = true
vaab-types.workspace = true

[dev-dependencies]
insta.workspace = true
