[package]
name = "vaab-syntax"
description = "Lexer, AST and parser for the Vaab programming language."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ariadne.workspace = true
logos.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
